// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicType.proto

#ifndef PROTOBUF_PublicType_2eproto__INCLUDED
#define PROTOBUF_PublicType_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace GLORY {
class DataStruct;
class DataStructDefaultTypeInternal;
extern DataStructDefaultTypeInternal _DataStruct_default_instance_;
}  // namespace GLORY

namespace GLORY {

namespace protobuf_PublicType_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_PublicType_2eproto

enum DataStruct_Type {
  DataStruct_Type_kUnknow = 0,
  DataStruct_Type_kType1 = 1,
  DataStruct_Type_kType2 = 2,
  DataStruct_Type_DataStruct_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  DataStruct_Type_DataStruct_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool DataStruct_Type_IsValid(int value);
const DataStruct_Type DataStruct_Type_Type_MIN = DataStruct_Type_kUnknow;
const DataStruct_Type DataStruct_Type_Type_MAX = DataStruct_Type_kType2;
const int DataStruct_Type_Type_ARRAYSIZE = DataStruct_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* DataStruct_Type_descriptor();
inline const ::std::string& DataStruct_Type_Name(DataStruct_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    DataStruct_Type_descriptor(), value);
}
inline bool DataStruct_Type_Parse(
    const ::std::string& name, DataStruct_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DataStruct_Type>(
    DataStruct_Type_descriptor(), name, value);
}
// ===================================================================

class DataStruct : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:GLORY.DataStruct) */ {
 public:
  DataStruct();
  virtual ~DataStruct();

  DataStruct(const DataStruct& from);

  inline DataStruct& operator=(const DataStruct& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DataStruct& default_instance();

  static inline const DataStruct* internal_default_instance() {
    return reinterpret_cast<const DataStruct*>(
               &_DataStruct_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(DataStruct* other);

  // implements Message ----------------------------------------------

  inline DataStruct* New() const PROTOBUF_FINAL { return New(NULL); }

  DataStruct* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DataStruct& from);
  void MergeFrom(const DataStruct& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DataStruct* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef DataStruct_Type Type;
  static const Type kUnknow =
    DataStruct_Type_kUnknow;
  static const Type kType1 =
    DataStruct_Type_kType1;
  static const Type kType2 =
    DataStruct_Type_kType2;
  static inline bool Type_IsValid(int value) {
    return DataStruct_Type_IsValid(value);
  }
  static const Type Type_MIN =
    DataStruct_Type_Type_MIN;
  static const Type Type_MAX =
    DataStruct_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    DataStruct_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return DataStruct_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return DataStruct_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return DataStruct_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // string name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // uint32 num = 1;
  void clear_num();
  static const int kNumFieldNumber = 1;
  ::google::protobuf::uint32 num() const;
  void set_num(::google::protobuf::uint32 value);

  // .GLORY.DataStruct.Type type = 3;
  void clear_type();
  static const int kTypeFieldNumber = 3;
  ::GLORY::DataStruct_Type type() const;
  void set_type(::GLORY::DataStruct_Type value);

  // @@protoc_insertion_point(class_scope:GLORY.DataStruct)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::uint32 num_;
  int type_;
  mutable int _cached_size_;
  friend struct protobuf_PublicType_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// DataStruct

// uint32 num = 1;
inline void DataStruct::clear_num() {
  num_ = 0u;
}
inline ::google::protobuf::uint32 DataStruct::num() const {
  // @@protoc_insertion_point(field_get:GLORY.DataStruct.num)
  return num_;
}
inline void DataStruct::set_num(::google::protobuf::uint32 value) {
  
  num_ = value;
  // @@protoc_insertion_point(field_set:GLORY.DataStruct.num)
}

// string name = 2;
inline void DataStruct::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DataStruct::name() const {
  // @@protoc_insertion_point(field_get:GLORY.DataStruct.name)
  return name_.GetNoArena();
}
inline void DataStruct::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:GLORY.DataStruct.name)
}
#if LANG_CXX11
inline void DataStruct::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:GLORY.DataStruct.name)
}
#endif
inline void DataStruct::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:GLORY.DataStruct.name)
}
inline void DataStruct::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:GLORY.DataStruct.name)
}
inline ::std::string* DataStruct::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:GLORY.DataStruct.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DataStruct::release_name() {
  // @@protoc_insertion_point(field_release:GLORY.DataStruct.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DataStruct::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:GLORY.DataStruct.name)
}

// .GLORY.DataStruct.Type type = 3;
inline void DataStruct::clear_type() {
  type_ = 0;
}
inline ::GLORY::DataStruct_Type DataStruct::type() const {
  // @@protoc_insertion_point(field_get:GLORY.DataStruct.type)
  return static_cast< ::GLORY::DataStruct_Type >(type_);
}
inline void DataStruct::set_type(::GLORY::DataStruct_Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:GLORY.DataStruct.type)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace GLORY

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::GLORY::DataStruct_Type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::GLORY::DataStruct_Type>() {
  return ::GLORY::DataStruct_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PublicType_2eproto__INCLUDED
